--DROP TABLE IF IT EXIST
IF OBJECT_ID('dbo.TEAM_TABLE_ID', 'U') IS NOT NULL 
  DROP TABLE dbo.TEAM_TABLE_ID; 

CREATE TABLE TEAM_TABLE_ID (
		ID INTEGER NOT NULL IDENTITY PRIMARY KEY,
		TEAMID INTEGER NOT NULL, 
		TEAM_TABLE_NAME VARCHAR(100) NOT NULL
		);
----ADD DATA FOR CHEKING
--INSERT INTO TEAM_TABLE_ID (TEAMID,TEAM_TABLE_NAME) VALUES (1847, '2018 TEST1')

--CHECK IF TABLE IS MADE
SELECT * FROM TEAM_TABLE_ID;

--DROP TABLE IF IT EXIST
IF OBJECT_ID('dbo.MEMBER', 'U') IS NOT NULL 
  DROP TABLE dbo.MEMBER; 

CREATE TABLE MEMBER (
		ID INTEGER NOT NULL IDENTITY PRIMARY KEY,
		ACC_TYPE TINYINT NOT NULL, 
		F_NAME VARCHAR(100) NOT NULL,
		L_NAME VARCHAR(100) NOT NULL,
		EMAIL VARCHAR(100) NOT NULL unique,
		PASS VARCHAR(500) NOT NULL,
		TEAM_ID INTEGER NOT NULL,
		APPROVED TINYINT NOT NULL
		);
----ADD DATA FOR CHEKING
INSERT INTO MEMBER (ACC_TYPE,F_NAME,L_NAME,EMAIL,PASS,TEAM_ID,APPROVED) VALUES (1,'jon', 'doe','mail@gmail.com','h6wep3PNndG5p7jBrTJuT3xNVPQYNBjj8INI5mp0cK4=',1847, 1);

--CHECK IF TABLE IS MADE
SELECT * FROM MEMBER;


IF OBJECT_ID('dbo.TEAM', 'U') IS NOT NULL 
  DROP TABLE dbo.TEAM; 

CREATE TABLE TEAM (
		ID INTEGER NOT NULL IDENTITY PRIMARY KEY,
		NUMBER INTEGER NOT NULL, 
		TEAM_NAME VARCHAR(100) NOT NULL,
		PRIVACY tinyint NOT NULL,
		);
----ADD DATA FOR CHEKING
INSERT INTO TEAM (NUMBER,TEAM_NAME,PRIVACY ) VALUES (1847, 'W.R.A.T.H', 1);

--CHECK IF TABLE IS MADE
SELECT * FROM TEAM;


